# GitHub Actions Workflow - Simplified (All Tests in One Job)
# This runs unit tests, then integration tests, then coverage - all sequentially

name: Tests

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  # Single job that runs ALL tests sequentially
  test-all:
    name: Run All Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4
      
      - name: 🔧 Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      
      - name: 📦 Install dependencies
        run: npm ci
      
      # ============================================
      # STEP 1: Run Unit Tests First
      # ============================================
      - name: 🧪 Run Unit Tests
        run: npm run test:unit -- --run --reporter=verbose
        env:
          NODE_ENV: test
          VITE_GEMINI_API_KEY: test-api-key-12345
      
      # ============================================
      # STEP 2: Run Integration Tests (Only if unit tests pass)
      # ============================================
      - name: 🔗 Run Integration Tests
        run: npm run test:integration -- --run --reporter=verbose
        env:
          NODE_ENV: test
          VITE_GEMINI_API_KEY: test-api-key-12345
      
      # ============================================
      # STEP 3: Generate Coverage (Optional - only on main branch)
      # ============================================
      - name: 📊 Generate Coverage Report
        if: github.ref == 'refs/heads/main'
        run: npm run test:coverage -- --run
        env:
          NODE_ENV: test
          VITE_GEMINI_API_KEY: test-api-key-12345
      
      # ============================================
      # STEP 4: Upload Coverage (Optional)
      # ============================================
      - name: 📤 Upload Coverage
        if: github.ref == 'refs/heads/main'
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage/coverage-final.json
          fail_ci_if_error: false
